version: "3.3"
services:
  proxy:
    image: "traefik:v2.9"
    container_name: "traefik"
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
    volumes:
      - "./traefik.yml:/traefik.yml"
      - "./letsencrypt:/letsencrypt"
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      - CLOUDFLARE_EMAIL=EMAIL # Cloudflare email to use for DNS challenge
      - CLOUDFLARE_API_KEY=KEY # Cloudflare API key to use for DNS challenge

networks:
  default:
    name: connector
    external: true